language: node_js
node_js:
- '10'
install:
- npm install
- npm run travis-build
scripts:
- npm test
before_deploy:
- cd ./dist
deploy:
  on:
    branch: master
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: DlBBLEnGEZlJ4Gr29HcoKpUEPNFHATw9i2wqYK+Yjlytoi7jHS2vbwFJmdLwCwLGY/tVuqns6xAzXNC0AVNXLHGlLG5BYOtbxvK5GZgo+O1O7D2mt2pnGtpgtIk70n6D/eT5hRBOeMtk84/U94uMHlNnEP/ApqgkzZyyw1j+ZDMJOG/TBNh6NDFY4+iez0EHvfNUoCq3ayDwozZHbsQ2OCT7Q1RMxNuqmzhqMjf/6WPhWk8pa7XJXjFphbsp0K4ZVdtFcBp1SlNYl+vM8yZlJ6DA4oDGRadGfhJbWSJBdhrkE6SW3cfxEnxfXACOXQfOW73SwO8tTHB2umNGKOCNGm68rBtVlMtcCli0GEZTdMDx4hxABp2c1NIGuhfAmQtjrg4Ja2Dy4hWUcJcIznJPZjA31O/z0C2RP9fJP4GGfFG3CCCsFL8KYXG4F0iMNOV8DxAPwRgiPBSCk3QUQlNboKesroUAh0aKbHMfyxPUzYSYO608Ex+VT5o+NJn6a2CnMKhpgdekJAQe7pCvFqhu0JvGurakDt1MfONaypfX6RG7JJIgfemUKTszeN1eJea3WDqn6mKVDByFdQYEKQD6M+M8Uur9g3u8de01OdfORZA5lAm5YS7Sd3bE0GSbriGf01q2U4GkJ/0kfdNzymyVmYM0uzyzvW2aZtB3xKajgY4=
  app: gw2-map
