language: node_js
node_js:
- '8'
install:
- npm install
- npm run travis-build
scripts:
- npm test
before_deploy:
- cd ./dist
deploy:
  on:
    branch: master
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: ${HEROKU_KEY}
  app: gw2-map
