language: node_js
node_js:
- '9'
install:
- npm install
- npm run travis-build
scripts:
- npm test -- --coverage
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: SXzNP87Z58BFZgWlfFPnvNkiEwnkegfHwg7GsNxIWJQQdhQkwFaBpFcKuwQf1aE+Gt6SMkePL0g7ovsOTZ866ITBAN7zjV/IJQIH/TX3eNOPOsjA1lmaa9YdcbPF1pMl2wlllsgTWGzUE+2D37CaeQzQn9a/i1kZCsBoV2t0VlKX5NJOePKzFCpMIkZKEOILifW0WQvh/B2YkFJvVSfSSdhbNGBLK5EB0sI95G95dr1kX0Cl+ncQm2cM3et+djg0FsjSGiG1uy0hSTZkwklehztVRGNIylQSF6bLP46D8JUc1hsufW2q8lhdw4FxFFHg+7phEibmDr0pcsH94a0VtZw6Qp1b0yCkDYwhBNJwghlenQsq2YwobgS3IG9nriGPKKVyd5qxfs8/QCSLMWT1GOHNqyvq8Wjt1IidLXg+IhUtia7xNbxg6NXkSleKoSsUWCM3T93RBP6pRT87xWjFZE8SKB3KvvI7eaMeE/IrFMrcLRpwZuoEEX74v8rFmBELJ6ZfEDsFbsLsRFZGC3KxkxhEdPr5HYDecfWl+IeX1vB+fpEvmLlVdS+/bNN/mKoFBQc9e8rSt6uudwCA3rMEFS1UWjlMQIrJaW9fyMHNn63pi2utzW7nFvoNrtilmYhCm8FJjZ8T7w29o6pS+bv2/R9aM0GHB+SJG1OPX+LrDpE=
