language: node_js
node_js:
- '10'
install:
- npm install
- npm run travis-build
scripts:
- npm test
before_deploy:
- cd ./dist
deploy:
  on:
    branch: master
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: ZHv17BtD2fBvutIDXkIz5n/8kZi98Qjn/Gb0ThjboDQT1Uh4wjuVwT9xRowyxex2pPPVLXAsIGaZx4E/dwoC1NO6A29e9ttoFz0ONxutbXo84zjor5VmPYpy5szFto1GYsRRquiS7pklPIrBGRYnQtpbWNyl1hrOmWpl4oR+OHWNGaRQ1ZmOpQCQuTauxJrPTca1KMcLQhMzia7QsOSsa4z8QNl626nOePqc2LL7ZODN9ao6+L3dTDg/RZ/6D2Eskp62fRYGuXlnMGN35nx/nxvIvmx+DARpFPNmH30M932ktf8ME0ccdwFND1Vw3UVnjHr2oafcb7LSTXTt5oH9XUEVReMEGVVDrXq6KGdwyzgMUwX+dLAuehJJAk5KWLUag02ZvzuJsgwHd67FyXfOpEtexTlz/UvHpVsNdd2NKekhql0cqI9P6yPbcuM1gi77rRG6YHy0SLTUhSR3wZSprxsdnnok/p1TPonDF80gYSHLFptX2dYxG5Xr2dDNvYUJCRQyi3o6wojB0sxXJXBn8snR7Q2wExY9KzMmbFIO/v4V+asxKt0O6lkDi746kyv6kp5tHMr3fXKLvs5WuVS51Bl98ayx2pYyDr6pnZewE84458OuzGJfNT75sybZTFdnipoqnn/YBzSGlzG2krlb3uYIHV9zdkNjUG8NZMMsz9A=
  app: gw2-map
